### ISSUE TITLE
Latest update causes large CPU consumption

### ISSUE THREAD

**Issue by jeanpaulvandeursen** [unarj/hooverZoom#2]
Today's (March 28 2016 - 0.44.3) update causes Firefox (45.0.1) to consume 100% CPU on OS X 10.11.4

**Comment by unarj** [comment]
haven't had a release in a while...
Version 0.44.3 Info
Last Updated: January 17, 2016

so I'm guessing it's not hooverZoom that is causing it.  new user?  any other addons enabled?

**Comment by jeanpaulvandeursen** [comment]
existing user, several other addons enabled, it is hoverzoom,can reproduce
the issue. Possibly related to XCode update I got pushed 2 days back?

**Comment by unarj** [comment]
I may have found the problem, tho it had different symptoms in Windows.  try out v0.45.1.

**Comment by jeanpaulvandeursen** [comment]
tried it, addon doesn't work anymore, cpu ok though :-) and yes, it is enabled...

**Comment by unarj** [comment]
working wonderfully here.  had to turn off the signed security features to get it to run, or just wait until the Mozilla team approves it and it's signed through the normal process.

**Comment by jeanpaulvandeursen** [comment]
turned off signed security but still doesn't work, console log says:
HTTP load failed with status 404. Load of media resource https://<site>/<path>/null failed
so the image name is not properly populated?

**Comment by unarj** [comment]
check out the most recent version, 45.4 has been approved by the Mozilla gods.  any improvement?

**Comment by jeanpaulvandeursen** [comment]
nope, sorry, still doesn’t work, network log still shows requests for /null. completely wiped FF from my system, reinstalled, installed hooverZoom fresh, no luck

**Comment by unarj** [comment]
don't suppose you want to donate a Mac to the hooverZoom cause?

**Comment by jeanpaulvandeursen** [comment]
LOL, if money was no issue you'd have one in a second, unfortunately it is
my most expensive possession....

**Comment by unarj** [comment]
try the latest build and let me know how it goes

**Comment by jeanpaulvandeursen** [comment]
tried, it, still doesn’t work
