### ISSUE TITLE
Causing my banking website to break

### ISSUE THREAD

**Issue by paulverbeke** [unarj/hooverZoom#9]
Hello,

First of all thanks a lot for your continuous work on this extension.
I've been using this for so long and so seamlessly that sometimes I completely forget that it's not part of Firefox by default.

I recently noticed that several functionalities on my banking website were broken.
Random disconnections without warning to prolong session, random form validation errors, wires between accounts not working, anyway, quite annoying.

After several hours comparing private/normal Firefox windows, disabling all extensions and looking by dichotomy, I finally found out that hooverZoom was the culprit.
I added cic.fr to the blockList in hooverZoom and everything was fixed.

I can't be certain but I think that everything was fine several months ago. 
I don't know if it's a recent update of hooverZoom or of my banking website (CIC) that's causing to hooverZoom to behave like this.

I'm a web developer and available to help you investigate if needed.

**Comment by unarj** [comment]
hey, thanks for the input.  your solution is the correct one, just put the site in the Block List and HZ will deactivate on those URLs.

that being said, no idea why it would break any site's functioning.  I added the Block List for esthetics as some sites handle mouseover image links better than others.  the way the add-on works is by adding some simple javascript to every A tag (HTML link) to check the target for media, it's possible there's some sort of security on the bank site that detects the modification and blocks it for security reasons.  if this is the case I don't think there's anything to be done on the HZ side without a completely new way to implement it.

**Comment by paulverbeke** [comment]
Thanks for your feedback.
Don't worry about it, you're right though: if HZ is injecting some JS in the page that would probably cause a security flag when submitting their forms.
Banks takes everything measures to prevent any tampering of their apps.
Sorry for disturbing you with this and thanks again
I'm closing this
